baseURL = "https://atugo.me"
languageCode = "zh-cn"
title = "土狗"
theme = "mini"

# 每页显示文章数量
paginate = 5

hasCJKLanguage = true

# 固定链接
[permalinks]
  posts = "/posts/:filename"


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"

    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false


[params]
  author = "土狗"
  bio = "热爱生活"
  description = "My Blog"


  enableComments = true
  enableGoogleAnalytics = false
  enableOpenGraph = true


[[menu.main]]
name = "归档"
url = "/posts"
weight = "1"
[[menu.main]]
name = "观影"
url = "/movies"
weight = "2"
[[menu.main]]
name = "关于"
url = "/about"
weight = "3"
[[menu.main]]
name = "建设"
url = "/construct"
pre = "<i class='fas fa-drafting-compass'></i>"
weight = "4"