baseURL = "https://atugo.me"
languageCode = "zh-cn"
title = "土狗"
theme = "mini"

# 每页显示文章数量
paginate = 5

hasCJKLanguage = true

# 固定链接
[permalinks]
  posts = "/posts/:filename"


[markup]
  [markup.highlight]
    guessSyntax = "true"
    style = "emacs"


[params]
  author = "土狗"
  bio = "热爱生活"
  description = "My Blog"


  enableComments = true
  enableGoogleAnalytics = false


[[menu.main]]
name = "归档"
url = "/posts"
weight = "1"
[[menu.main]]
name = "观影"
url = "/movies"
weight = "2"
[[menu.main]]
name = "关于"
url = "/about"
weight = "3"