baseURL = "https://atugo.me"
languageCode = "zh-cn"
title = "土狗"
theme = "mini"

# 每页显示文章数量
paginate = 5

hasCJKLanguage = true
googleAnalytics = "UA-59524632-1"

# 固定链接
[permalinks]
  posts = "/posts/:filename"


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "perldoc"
    tabWidth = 4

  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"

    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.tableOfContents]
      endLevel = 3
      ordered = false
      startLevel = 2


[params]
  author = "土狗"
  bio = "热爱生活"
  description = "My Blog"


  enableComments = true
  enableGoogleAnalytics = true
  enableOpenGraph = true



[[menu.main]]
name = "归档"
url = "/posts"
weight = "100"
[[menu.main]]
name = "观影"
url = "/movies"
weight = "200"
[[menu.main]]
name = "游戏"
url = "/game"
weight = "300"
[[menu.main]]
name = "关于"
url = "/about"
weight = "400"
[[menu.main]]
name = "建设"
url = "/construct"
pre = "<i class='fas fa-drafting-compass'></i>"
weight = "500"