baseURL = "http://atugo.me/"
languageCode = "zh-CN"
title = "阿凸"

theme = "hello-friend"
summaryLength = 140
hasCJKLanguage = true

name = "首页"
url = "/"
weight = "1"
[[menu.main]]
name = "文章"
url = "/posts"
weight = "2"
[[menu.main]]
name = "观影"
url = "/movies"
weight = "3"
[[menu.main]]
name = "归档"
url = "/archives"
weight = "4"
[[menu.main]]
name = "关于"
url = "/about"
weight = "5"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  # showMenuItems = 4
  # Enable to show reading time in minutes for posts
  showReadingTime = true
  logoText = "hello friend"

  MenuMore = "更多"
  DateFormatList = "2006-01-02 15:04:05"
  DateFormatSingle = "2006-01-02 15:04:05"
  ReadMore = "阅读全文"

  EditPath = 'https://github.com/lmm214/immmmm/edit/master/content'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["Atom", "HTML","JSON"] # <domain>/atom.xml
  page = ["HTML"]
  
[outputFormats.Atom]
  mediatype = "application/rss"
  baseName = "atom"

[params.twikoo]
	enable = false