baseURL: https://atugo.me
languageCode: zh-cn
title: 土狗
theme: mini

# 每页显示文章数量
paginate: 5

hasCJKLanguage: true

# 固定链接
permalinks:
  posts: /posts/:filename/


markup:
  highlight:
    guessSyntax: true
    style: emacs


params:
  author: 土狗
  bio: 热爱生活
  description: My Blog

  enableComments: true
  enableGoogleAnalytics: false

  # Optional
  home: '首页' # Default: Home
  about: '关于' # Default: About
  archive: '归档' # Default: Archive
  tags: '标签' # Default: Tags
  movies: '电影' # Default: Movies
  subscribe: '' # Default: Subscribe
  olderPosts: '' # Default: Older Posts
  newerPosts: '' # Default: Newer Posts
  copyright: '' # Default: © Copyright 2021 ❤️ author
  title404: '' # Default: 404 - Page Not Found
  subtitle404: '' # Default: The content you're looking for doesn't seem to exist.
  readMore: '' # Default: Read More

  # Extra links in navigation
  links:
    # e.g.
    # - name: Project
    #   path: /project
