baseURL = "https://atugo.me"
DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "en-us"
title = "土狗"
# copyright = "土狗" 
theme = "diary"
# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "英雄主义"
enableGitalk = false
enableTwikoo = false
enableWaline = false
# googleSearchCode = "f4469f42e31d05da1"

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'
disableAutoCollapse = true


[taxonomies]
   tag = "tags"
   category = "categories"


[[menu.main]]
name = "归档"
url = "/posts"
weight = "1"

[[menu.main]]
name = "分类"
url = "/categories"
weight = "2"

[[menu.main]]
name = "标签"
url = "/tags"
weight = "3"

[[menu.main]]
name = "关于"
url = "/about"
weight = "4"